/* Colours */
let amarelo = $('amarelo')
let azul = $('azul')
let branco = $('branco')
let cinza = $('cinza')
let laranja = $('laranja')
let verde = $('verde')
let vermelho = $('vermelho')
let preto = $('preto')
let rosa = $('rosa')
let vinho = $('vinho')

/* sizes inputs */
let p = $('p-input')
let m = $('m-input')
let g = $('g-input')
let gg = $('gg-input')
let u = $('u-input')
let tresSeis = $('36-input')
let tresOcho = $('38-input')
let cuatroCero = $('40-input')
let cuatroDos = $('42-input')
let cuatroCuatro = $('44-input')
let cuatroSeis = $('46-input')

/* sizes box */
let pBox = $('p-size')
let mBox = $('m-size')
let gBox = $('g-size')
let ggBox = $('gg-size')
let uBox = $('u-size')
let tresSeisBox = $('36-size')
let tresOchoBox = $('38-size')
let cuatroCeroBox = $('40-size')
let cuatroDosBox = $('42-size')
let cuatroCuatroBox = $('44-size')
let cuatroSeisBox = $('46-size')

/* prices Input */
let price1 = $('price1')
let price2 = $('price2')
let price3 = $('price3')
let price4 = $('price4')
let price5 = $('price5')